#%RAML 0.8

title: Web Automation Tools
version: 0.0.1-SNAPSHOT
baseUri: https://127.0.0.1:3005/{version}/
mediaType: application/json
schemas:
  - Smila/Worker: !include schema/Worker.json

resourceTypes:
  - member: !include resourceTypes/member.raml
  - base: !include resourceTypes/base.raml
  - collection: !include resourceTypes/collection.raml
  - activityType: !include resourceTypes/activityType.raml

traits:
  - pageable: !include traits/pageable.raml

/workers: 
  type: { collection: { type: notification } }
  get: 
    description: |
      Web Automation Tools Workers
    responses: 
      200: 
        body: 
          application/json: 
            schema: Smila/Worker