#%RAML 0.8
title: Web Automation Tools
version: 0.0.1-SNAPSHOT
baseUri: https://127.0.0.1:3005/{version}/
mediaType: application/json
schemas:
  - Smila/Worker: !include schema/Worker.json
  - Smila/Task: !include schema/Task.json
  - Smila/Process: !include schema/Process.json
  - Smila/Job: !include schema/Job.json
  - Smila/Model: !include schema/Model.json
  - Smila/Record: !include schema/Record.json

traits:
  - pageable: !include traits/pageable.raml

/workers: 
  type: collection
  get: 
    description: |
      Web Automation Tools Workers
    responses: 
      200: 
        body: 
          application/json: 
            schema: Smila/Worker
            example: !include examples/Worker.json
